---
abstract: 'send an email on dist release'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-EmailNotify
requires:
  Dist::Zilla::Role::Releaser: 0
  Email::Stuff: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/xsawyerx/dist-zilla-plugin-emailnotify
version: 0.001
